import { Routes, Route, Navigate } from "react-router-dom"; // Importación de componentes de React Router para definir las rutas de la aplicación, lo que permite a los componentes de esta pantalla redirigir a los usuarios a otras pantallas de la aplicación según las interacciones del usuario y controlar el acceso a ciertas rutas según el estado de autenticación del usuario
import type { JSX } from "preact";// Importación del tipo JSX para definir los tipos de los componentes, lo que permite a los desarrolladores tener una mejor experiencia de desarrollo al proporcionar autocompletado y verificación de tipos en los componentes de la aplicación

import { AuthProvider, useAuth } from "./providers/AuthProvider";// Importación del contexto de autenticación y el hook useAuth para proporcionar y acceder a la información de autenticación en toda la aplicación, lo que permite a los componentes de esta pantalla controlar el acceso a ciertas rutas según el estado de autenticación del usuario y mostrar información personalizada en función del usuario autenticado
import { RoleSelector }          from "./screens/RoleSelector";// Importación del componente RoleSelector para mostrar una pantalla de selección de rol al usuario, lo que permite a los usuarios elegir su rol (familia o gestor) al ingresar a la aplicación, lo que proporciona una experiencia personalizada y relevante para cada tipo de usuario desde el inicio de la aplicación
import { LoginScreen }           from "./screens/Login";// Importación del componente LoginScreen para mostrar una pantalla de inicio de sesión al usuario, lo que permite a los usuarios autenticarse en la aplicación para acceder a las funcionalidades protegidas y personalizadas según su rol, lo que mejora la seguridad y la experiencia del usuario al requerir autenticación para acceder a ciertas partes de la aplicación
import { HomeFamiliaScreen }     from "./screens/familia/HomeFamilia";// Importación del componente HomeFamiliaScreen para mostrar la pantalla de inicio de la sección de familia, lo que proporciona a los usuarios con rol de familia una experiencia personalizada al mostrarles un menú principal con opciones relevantes para su rol, como actividades, comunidad, escanear QR y perfil, lo que mejora la experiencia del usuario al proporcionar una interfaz adaptada a sus necesidades y funcionalidades específicas dentro de la aplicación
import { ActividadesScreen }     from "./screens/familia/Actividades";// Importación del componente ActividadesScreen para mostrar la pantalla de actividades dentro de la sección de familia, lo que permite a los usuarios con rol de familia acceder a las actividades disponibles, participar en ellas y mantenerse informados sobre las experiencias compartidas por los gestores, lo que mejora la experiencia del usuario al proporcionar una interfaz clara y fácil de usar para interactuar con las actividades dentro de la aplicación
import { ComunidadScreen }       from "./screens/familia/Comunidad";// Importación del componente ComunidadScreen para mostrar la pantalla de comunidad dentro de la sección de familia, lo que permite a los usuarios con rol de familia acceder a un espacio de conversación e interacción con otros usuarios, compartir experiencias, motivar a otros y resolver dudas, lo que mejora la experiencia del usuario al proporcionar una plataforma de comunicación y colaboración dentro de la aplicación
import { EscanearQRScreen }      from "./screens/familia/EscanearQR";// Importación del componente EscanearQRScreen para mostrar la pantalla de escaneo de QR dentro de la sección de familia, lo que permite a los usuarios con rol de familia escanear códigos QR relacionados con las actividades, lo que mejora la experiencia del usuario al proporcionar una forma fácil y rápida de interactuar con las actividades y acceder a contenido adicional o participar en experiencias compartidas por los gestores dentro de la aplicación
import { Perfil }                from "./screens/familia/Perfil";// Importación del componente Perfil para mostrar la pantalla de perfil dentro de la sección de familia, lo que permite a los usuarios con rol de familia ver y gestionar su información personal, como su nombre completo y correo electrónico, y proporcionar una opción para cerrar sesión, lo que mejora la experiencia del usuario al proporcionar una interfaz clara y fácil de usar para acceder a su información de perfil y gestionar su sesión dentro de la aplicación
import { HomeGestorScreen }      from "./screens/gestor/HomeGestor";// Importación del componente HomeGestorScreen para mostrar la pantalla de inicio de la sección de gestor, lo que proporciona a los usuarios con rol de gestor una experiencia personalizada al mostrarles un menú principal con opciones relevantes para su rol, como crear actividades, comunidad, dashboard y perfil, lo que mejora la experiencia del usuario al proporcionar una interfaz adaptada a sus necesidades y funcionalidades específicas dentro de la aplicación
import { CrearActividadScreen }  from "./screens/gestor/CrearActividad";// Importación del componente CrearActividadScreen para mostrar la pantalla de creación de actividades dentro de la sección de gestor, lo que permite a los usuarios con rol de gestor crear nuevas actividades, compartir experiencias y mantener informados a los hogares sobre el tema de las actividades, lo que mejora la experiencia del usuario al proporcionar una interfaz clara y fácil de usar para gestionar las actividades dentro de la aplicación
import { DashboardScreen }       from "./screens/gestor/Dashboard";// Importación del componente DashboardScreen para mostrar la pantalla de dashboard dentro de la sección de gestor, lo que permite a los usuarios con rol de gestor analizar el compromiso de las familias y el impacto de sus actividades a través de métricas clave y un análisis visual del embudo AIDA, lo que mejora la experiencia del usuario al proporcionar información relevante y visual para tomar decisiones informadas sobre sus actividades dentro de la aplicación
import { PerfilGestor }          from "./screens/gestor/PerfilGestor";// Importación del componente PerfilGestor para mostrar la pantalla de perfil dentro de la sección de gestor, lo que permite a los usuarios con rol de gestor ver y gestionar su información personal, como su nombre completo y correo electrónico, y proporcionar una opción para cerrar sesión, lo que mejora la experiencia del usuario al proporcionar una interfaz clara y fácil de usar para acceder a su información de perfil y gestionar su sesión dentro de la aplicación
import { ComunidadGestorScreen } from "./screens/gestor/ComunidadGestor";// Importación del componente ComunidadGestorScreen para mostrar la pantalla de comunidad dentro de la sección de gestor, lo que permite a los usuarios con rol de gestor conversar, motivar y responder directamente a las dudas de los hogares, lo que mejora la experiencia del usuario al proporcionar una plataforma de comunicación y colaboración dentro de la aplicación para que los gestores puedan interactuar con las familias y brindarles apoyo e información relevante sobre las actividades y experiencias compartidas en la aplicación
import type { UserRole } from "./types";// Importación del tipo UserRole para definir los roles de usuario en la aplicación, lo que permite a los componentes de esta pantalla controlar el acceso a ciertas rutas según el rol del usuario autenticado y proporcionar una experiencia personalizada y relevante para cada tipo de usuario dentro de la aplicación

const PrivateRoute = ({ children, role }: { children: JSX.Element; role?: UserRole }) => {// Componente de ruta privada que controla el acceso a ciertas rutas según el estado de autenticación del usuario y su rol, lo que permite a los componentes de esta pantalla redirigir a los usuarios no autenticados a la pantalla de inicio de sesión y redirigir a los usuarios autenticados a la ruta correspondiente según su rol, lo que mejora la seguridad y la experiencia del usuario al garantizar que solo los usuarios autorizados puedan acceder a ciertas partes de la aplicación
  const { auth, isLoading } = useAuth();// Utiliza el hook useAuth para obtener el objeto de autenticación y su estado de carga, lo que permite a los componentes de esta pantalla controlar el acceso a ciertas rutas según el estado de autenticación del usuario y su rol, y mostrar un indicador de carga mientras se obtiene esta información
  if (isLoading) return null;// Si el estado de autenticación aún se está cargando, no renderiza nada (podría mostrar un spinner o indicador de carga aquí), lo que mejora la experiencia del usuario al evitar mostrar contenido incorrecto o redirigir prematuramente mientras se obtiene la información de autenticación
  if (!auth) return <Navigate to="/" replace />;// Si el usuario no está autenticado, redirige a la pantalla de selección de rol (que a su vez redirige a login), lo que mejora la experiencia del usuario al guiarlo hacia el proceso de autenticación para acceder a las funcionalidades protegidas de la aplicación
  if (role && auth.user.role !== role) return <Navigate to={`/${auth.user.role}`} replace />;// Si se especifica un rol y el rol del usuario autenticado no coincide, redirige a la ruta correspondiente al rol del usuario, lo que mejora la experiencia del usuario al garantizar que solo accedan a las partes de la aplicación que son relevantes para su rol y evitar confusiones o accesos no autorizados
  return children;// Si el usuario está autenticado y tiene el rol correcto (si se especifica), renderiza el componente hijo, lo que permite a los usuarios autorizados acceder a la ruta protegida y disfrutar de una experiencia personalizada y relevante dentro de la aplicación según su estado de autenticación y rol
};// Componente de ruta privada que controla el acceso a ciertas rutas según el estado de autenticación del usuario y su rol, lo que permite a los componentes de esta pantalla redirigir a los usuarios no autenticados a la pantalla de inicio de sesión y redirigir a los usuarios autenticados a la ruta correspondiente según su rol, lo que mejora la seguridad y la experiencia del usuario al garantizar que solo los usuarios autorizados puedan acceder a ciertas partes de la aplicación

const PublicRoute = ({ children }: { children: JSX.Element }) => {// Componente de ruta pública que controla el acceso a ciertas rutas para usuarios no autenticados, lo que permite a los componentes de esta pantalla redirigir a los usuarios autenticados a la ruta correspondiente según su rol y mostrar el contenido solo a los usuarios no autenticados, lo que mejora la experiencia del usuario al guiarlo hacia la autenticación si intenta acceder a contenido público mientras ya está autenticado
  const { auth, isLoading } = useAuth();// Utiliza el hook useAuth para obtener el objeto de autenticación y su estado de carga, lo que permite a los componentes de esta pantalla controlar el acceso a ciertas rutas para usuarios no autenticados y mostrar un indicador de carga mientras se obtiene esta información
  if (isLoading) return null;// Si el estado de autenticación aún se está cargando, no renderiza nada (podría mostrar un spinner o indicador de carga aquí), lo que mejora la experiencia del usuario al evitar mostrar contenido incorrecto o redirigir prematuramente mientras se obtiene la información de autenticación
  if (auth) return <Navigate to={`/${auth.user.role}`} replace />;// Si el usuario ya está autenticado, redirige a la ruta correspondiente a su rol, lo que mejora la experiencia del usuario al guiarlo hacia la parte de la aplicación que es relevante para su rol y evitar mostrar contenido público que no es relevante para usuarios autenticados
  return children;// Si el usuario no está autenticado, renderiza el componente hijo, lo que permite a los usuarios no autenticados acceder a contenido público como la pantalla de selección de rol o la pantalla de inicio de sesión, y proporciona una experiencia personalizada y relevante para cada tipo de usuario dentro de la aplicación según su estado de autenticación
};// Componente de ruta pública que controla el acceso a ciertas rutas para usuarios no autenticados, lo que permite a los componentes de esta pantalla redirigir a los usuarios autenticados a la ruta correspondiente según su rol y mostrar el contenido solo a los usuarios no autenticados, lo que mejora la experiencia del usuario al guiarlo hacia la autenticación si intenta acceder a contenido público mientras ya está autenticado

const AppRoutes = () => (// Componente principal de rutas de la aplicación, que define todas las rutas disponibles en la aplicación y utiliza los componentes PrivateRoute y PublicRoute para controlar el acceso a cada ruta según el estado de autenticación del usuario y su rol, lo que mejora la seguridad y la experiencia del usuario al garantizar que solo los usuarios autorizados puedan acceder a ciertas partes de la aplicación y guiar a los usuarios hacia la autenticación si intentan acceder a contenido público mientras ya están autenticados
  <div style={{ display: "flex", minHeight: "100vh", width: "100%", justifyContent:"center"}}>// Contenedor principal de la aplicación con estilos para ocupar toda la pantalla, centrar el contenido y proporcionar una experiencia visual agradable en diferentes tamaños de pantalla, lo que mejora la experiencia del usuario al garantizar que la aplicación se vea bien y sea fácil de usar en una variedad de dispositivos
    <Routes>// Componente de rutas que define todas las rutas disponibles en la aplicación, lo que permite a los componentes de esta pantalla redirigir a los usuarios a otras pantallas de la aplicación según las interacciones del usuario y controlar el acceso a ciertas rutas según el estado de autenticación del usuario y su rol
      <Route path="/"      element={<PublicRoute><RoleSelector /></PublicRoute>} />// Ruta para la pantalla de selección de rol, que es accesible solo para usuarios no autenticados, lo que permite a los nuevos usuarios elegir su rol (familia o gestor) al ingresar a la aplicación y proporciona una experiencia personalizada y relevante para cada tipo de usuario desde el inicio de la aplicación
      <Route path="/login" element={<PublicRoute><LoginScreen /></PublicRoute>} />// Ruta para la pantalla de inicio de sesión, que es accesible solo para usuarios no autenticados, lo que permite a los usuarios autenticarse en la aplicación para acceder a las funcionalidades protegidas y personalizadas según su rol, lo que mejora la seguridad y la experiencia del usuario al requerir autenticación para acceder a ciertas partes de la aplicación

      <Route path="/familia"             element={<PrivateRoute role="familia"><HomeFamiliaScreen /></PrivateRoute>} />// Ruta para la pantalla de inicio de la sección de familia, que es accesible solo para usuarios autenticados con rol de familia, lo que proporciona a los usuarios con rol de familia una experiencia personalizada al mostrarles un menú principal con opciones relevantes para su rol, como actividades, comunidad, escanear QR y perfil, lo que mejora la experiencia del usuario al proporcionar una interfaz adaptada a sus necesidades y funcionalidades específicas dentro de la aplicación
      <Route path="/familia/actividades" element={<PrivateRoute role="familia"><ActividadesScreen /></PrivateRoute>} />// Ruta para la pantalla de actividades dentro de la sección de familia, que es accesible solo para usuarios autenticados con rol de familia, lo que permite a los usuarios con rol de familia acceder a las actividades disponibles, participar en ellas y mantenerse informados sobre las experiencias compartidas por los gestores, lo que mejora la experiencia del usuario al proporcionar una interfaz clara y fácil de usar para interactuar con las actividades dentro de la aplicación
      <Route path="/familia/comunidad"   element={<PrivateRoute role="familia"><ComunidadScreen /></PrivateRoute>} />// Ruta para la pantalla de comunidad dentro de la sección de familia, que es accesible solo para usuarios autenticados con rol de familia, lo que permite a los usuarios con rol de familia acceder a un espacio de conversación e interacción con otros usuarios, compartir experiencias, motivar a otros y resolver dudas, lo que mejora la experiencia del usuario al proporcionar una plataforma de comunicación y colaboración dentro de la aplicación
      <Route path="/familia/escanear-qr" element={<PrivateRoute role="familia"><EscanearQRScreen /></PrivateRoute>} />// Ruta para la pantalla de escaneo de QR dentro de la sección de familia, que es accesible solo para usuarios autenticados con rol de familia, lo que permite a los usuarios con rol de familia escanear códigos QR relacionados con las actividades, lo que mejora la experiencia del usuario al proporcionar una forma fácil y rápida de interactuar con las actividades y acceder a contenido adicional o participar en experiencias compartidas por los gestores dentro de la aplicación
      <Route path="/familia/perfil"      element={<PrivateRoute role="familia"><Perfil /></PrivateRoute>} />// Ruta para la pantalla de perfil dentro de la sección de familia, que es accesible solo para usuarios autenticados con rol de familia, lo que permite a los usuarios con rol de familia ver y gestionar su información personal, como su nombre completo y correo electrónico, y proporcionar una opción para cerrar sesión, lo que mejora la experiencia del usuario al proporcionar una interfaz clara y fácil de usar para acceder a su información de perfil y gestionar su sesión dentro de la aplicación

      <Route path="/gestor"              element={<PrivateRoute role="gestor"><HomeGestorScreen /></PrivateRoute>} />// Ruta para la pantalla de inicio de la sección de gestor, que es accesible solo para usuarios autenticados con rol de gestor, lo que proporciona a los usuarios con rol de gestor una experiencia personalizada al mostrarles un menú principal con opciones relevantes para su rol, como crear actividades, comunidad, dashboard y perfil, lo que mejora la experiencia del usuario al proporcionar una interfaz adaptada a sus necesidades y funcionalidades específicas dentro de la aplicación
      <Route path="/gestor/actividades"  element={<PrivateRoute role="gestor"><CrearActividadScreen /></PrivateRoute>} />// Ruta para la pantalla de creación de actividades dentro de la sección de gestor, que es accesible solo para usuarios autenticados con rol de gestor, lo que permite a los usuarios con rol de gestor crear nuevas actividades, compartir experiencias y mantener informados a los hogares sobre el tema de las actividades, lo que mejora la experiencia del usuario al proporcionar una interfaz clara y fácil de usar para gestionar las actividades dentro de la aplicación
      <Route path="/gestor/comunidad"    element={<PrivateRoute role="gestor"><ComunidadGestorScreen /></PrivateRoute>} />// Ruta para la pantalla de comunidad dentro de la sección de gestor, que es accesible solo para usuarios autenticados con rol de gestor, lo que permite a los usuarios con rol de gestor conversar, motivar y responder directamente a las dudas de los hogares, lo que mejora la experiencia del usuario al proporcionar una plataforma de comunicación y colaboración dentro de la aplicación para que los gestores puedan interactuar con las familias y brindarles apoyo e información relevante sobre las actividades y experiencias compartidas en la aplicación
      <Route path="/gestor/dashboard"    element={<PrivateRoute role="gestor"><DashboardScreen /></PrivateRoute>} />// Ruta para la pantalla de dashboard dentro de la sección de gestor, que es accesible solo para usuarios autenticados con rol de gestor, lo que permite a los usuarios con rol de gestor analizar el compromiso de las familias y el impacto de sus actividades a través de métricas clave y un análisis visual del embudo AIDA, lo que mejora la experiencia del usuario al proporcionar información relevante y visual para tomar decisiones informadas sobre sus actividades dentro de la aplicación
      <Route path="/gestor/perfil"       element={<PrivateRoute role="gestor"><PerfilGestor /></PrivateRoute>} />// Ruta para la pantalla de perfil dentro de la sección de gestor, que es accesible solo para usuarios autenticados con rol de gestor, lo que permite a los usuarios con rol de gestor ver y gestionar su información personal, como su nombre completo y correo electrónico, y proporcionar una opción para cerrar sesión, lo que mejora la experiencia del usuario al proporcionar una interfaz clara y fácil de usar para acceder a su información de perfil y gestionar su sesión dentro de la aplicación

      <Route path="*" element={<Navigate to="/" replace />} />// Ruta para cualquier ruta no definida, que redirige a la pantalla de selección de rol, lo que mejora la experiencia del usuario al guiarlo hacia el inicio de la aplicación si intenta acceder a una ruta no válida o no autorizada, y proporciona una forma de manejar errores de navegación de manera elegante dentro de la aplicación
    </Routes>// Componente de rutas que define todas las rutas disponibles en la aplicación, lo que permite a los componentes de esta pantalla redirigir a los usuarios a otras pantallas de la aplicación según las interacciones del usuario y controlar el acceso a ciertas rutas según el estado de autenticación del usuario y su rol
  </div>// Contenedor principal de la aplicación con estilos para ocupar toda la pantalla, centrar el contenido y proporcionar una experiencia visual agradable en diferentes tamaños de pantalla, lo que mejora la experiencia del usuario al garantizar que la aplicación se vea bien y sea fácil de usar en una variedad de dispositivos
);

export const App = () => (// Componente principal de la aplicación que envuelve el componente de rutas con el proveedor de autenticación, lo que permite a los componentes de esta pantalla acceder a la información de autenticación y controlar el acceso a ciertas rutas según el estado de autenticación del usuario y su rol, lo que mejora la seguridad y la experiencia del usuario al garantizar que solo los usuarios autorizados puedan acceder a ciertas partes de la aplicación y guiar a los usuarios hacia la autenticación si intentan acceder a contenido público mientras ya están autenticados
  <AuthProvider>// Proveedor de autenticación que envuelve toda la aplicación, lo que permite a los componentes de esta pantalla acceder a la información de autenticación y controlar el acceso a ciertas rutas según el estado de autenticación del usuario y su rol, lo que mejora la seguridad y la experiencia del usuario al garantizar que solo los usuarios autorizados puedan acceder a ciertas partes de la aplicación y guiar a los usuarios hacia la autenticación si intentan acceder a contenido público mientras ya están autenticados
    <AppRoutes />// Componente de rutas que define todas las rutas disponibles en la aplicación, lo que permite a los componentes de esta pantalla redirigir a los usuarios a otras pantallas de la aplicación según las interacciones del usuario y controlar el acceso a ciertas rutas según el estado de autenticación del usuario y su rol
  </AuthProvider>// Proveedor de autenticación que envuelve toda la aplicación, lo que permite a los componentes de esta pantalla acceder a la información de autenticación y controlar el acceso a ciertas rutas según el estado de autenticación del usuario y su rol, lo que mejora la seguridad y la experiencia del usuario al garantizar que solo los usuarios autorizados puedan acceder a ciertas partes de la aplicación y guiar a los usuarios hacia la autenticación si intentan acceder a contenido público mientras ya están autenticados
);// Componente principal de la aplicación que envuelve el componente de rutas con el proveedor de autenticación, lo que permite a los componentes de esta pantalla acceder a la información de autenticación y controlar el acceso a ciertas rutas según el estado de autenticación del usuario y su rol, lo que mejora la seguridad y la experiencia del usuario al garantizar que solo los usuarios autorizados puedan acceder a ciertas partes de la aplicación y guiar a los usuarios hacia la autenticación si intentan acceder a contenido público mientras ya están autenticados
