import dotenv from 'dotenv';// Importación del módulo 'dotenv' para cargar las variables de entorno desde un archivo .env, lo que permite a la aplicación obtener esta información de manera segura y flexible desde el entorno de ejecución, mejorando la seguridad al no hardcodear esta información en el código fuente y facilitando la configuración de la aplicación en diferentes entornos (desarrollo, producción, etc.) al permitir cambiar estas variables sin modificar el código fuente

dotenv.config();// Carga de las variables de entorno desde el archivo .env, lo que permite a la aplicación obtener esta información de manera segura y flexible desde el entorno de ejecución, mejorando la seguridad al no hardcodear esta información en el código fuente y facilitando la configuración de la aplicación en diferentes entornos (desarrollo, producción, etc.) al permitir cambiar estas variables sin modificar el código fuente

export const PORT = Number(process.env.PORT) || 3000;
export const NODE_ENV = process.env.NODE_ENV || 'development';

export const DB_HOST = process.env.DB_HOST || 'localhost';// Exportación de la variable de entorno para la dirección del host de la base de datos, lo que permite a la aplicación obtener esta información de manera segura y flexible desde el entorno de ejecución, mejorando la seguridad al no hardcodear esta información en el código fuente y facilitando la configuración de la aplicación en diferentes entornos (desarrollo, producción, etc.) al permitir cambiar esta variable sin modificar el código fuente
export const DB_PORT = Number(process.env.DB_PORT || 6543);// Exportación de la variable de entorno para el número de puerto de la base de datos, lo que permite a la aplicación obtener esta información de manera segura y flexible desde el entorno de ejecución, mejorando la seguridad al no hardcodear esta información en el código fuente y facilitando la configuración de la aplicación en diferentes entornos (desarrollo, producción, etc.) al permitir cambiar esta variable sin modificar el código fuente
export const DB_USER = process.env.DB_USER || 'postgres';// Exportación de la variable de entorno para el nombre de usuario de la base de datos, lo que permite a la aplicación obtener esta información de manera segura y flexible desde el entorno de ejecución, mejorando la seguridad al no hardcodear esta información en el código fuente y facilitando la configuración de la aplicación en diferentes entornos (desarrollo, producción, etc.) al permitir cambiar esta variable sin modificar el código fuente
export const DB_PASSWORD = process.env.DB_PASSWORD || 'password';// Exportación de la variable de entorno para la contraseña de la base de datos, lo que permite a la aplicación obtener esta información de manera segura y flexible desde el entorno de ejecución, mejorando la seguridad al no hardcodear esta información en el código fuente y permitir cambiarla de manera segura a través de variables de entorno
export const DB_NAME = process.env.DB_NAME || 'mydatabase';// Exportación de la variable de entorno para el nombre de la base de datos, lo que permite a la aplicación obtener esta información de manera segura y flexible desde el entorno de ejecución, mejorando la seguridad al no hardcodear esta información en el código fuente y facilitando la configuración de la aplicación en diferentes entornos (desarrollo, producción, etc.) al permitir cambiar esta variable sin modificar el código fuente

export const SUPABASE_URL = process.env.SUPABASE_URL || '';// Exportación de la variable de entorno para la URL de Supabase, lo que permite a la aplicación obtener esta información de manera segura y flexible desde el entorno de ejecución, mejorando la seguridad al no hardcodear esta información en el código fuente y facilitando la configuración de la aplicación en diferentes entornos (desarrollo, producción, etc.) al permitir cambiar esta variable sin modificar el código fuente
export const SUPABASE_KEY = process.env.SUPABASE_KEY || '';// Exportación de la variable de entorno para la clave de Supabase, lo que permite a la aplicación obtener esta información de manera segura y flexible desde el entorno de ejecución, mejorando la seguridad al no hardcodear esta información en el código fuente y facilitando la configuración de la aplicación en diferentes entornos (desarrollo, producción, etc.) al permitir cambiar esta variable sin modificar el código fuente
