import { pool } from "../../config/database";// Importación del objeto pool desde el módulo de configuración de la base de datos, lo que permite a este módulo interactuar con la base de datos utilizando este objeto para ejecutar consultas SQL y realizar operaciones relacionadas con las asistencias en la aplicación, mejorando la gestión de la base de datos al centralizar la configuración y el acceso a la base de datos en un módulo específico
import { getActividadByQrPayloadService } from "../actividades/actividades.service";// Importación del servicio getActividadByQrPayloadService desde el módulo de servicios de actividades, lo que permite a este módulo utilizar este servicio para obtener la información de una actividad específica utilizando el payload de QR, mejorando la organización del código al separar las responsabilidades entre los servicios y facilitando el mantenimiento y la escalabilidad de la aplicación al centralizar la lógica de negocio relacionada con las actividades en los servicios
import { Asistencia, ScanQRDTO, ScanResult } from "./asistencias.types";// Importación de los tipos Asistencia, ScanQRDTO y ScanResult desde el módulo de tipos de asistencias, lo que permite a este módulo utilizar estos tipos para definir la estructura de los datos relacionados con las asistencias, mejorando la gestión de tipos en la aplicación al centralizar la definición de tipos relacionados con las asistencias en un módulo específico y facilitando su uso en todo el módulo de asistencias
import Boom from "@hapi/boom";// Importación de la biblioteca Boom para manejar errores HTTP de manera estructurada, lo que permite a este módulo utilizar Boom para lanzar errores HTTP con mensajes y códigos de estado específicos, mejorando la gestión de errores en la aplicación al proporcionar una forma clara y consistente de manejar los errores que puedan ocurrir durante la ejecución de las operaciones relacionadas con las asistencias

export const scanQRService = async (// Función asíncrona para manejar el escaneo de una actividad para registrar la asistencia, lo que permite a esta función procesar la lógica relacionada con el escaneo de una actividad utilizando el payload de QR proporcionado, obtener la información de la actividad correspondiente, verificar si el usuario ya ha registrado su asistencia a esa actividad, y registrar la asistencia si es válida, mejorando la gestión de las asistencias en la aplicación al proporcionar una función clara y estructurada para manejar esta operación
  data: ScanQRDTO,// Parámetro para proporcionar los datos necesarios para el escaneo de la actividad, lo que permite a esta función recibir la información del payload de QR que se desea escanear para registrar la asistencia, mejorando la flexibilidad de la aplicación al permitir a los desarrolladores proporcionar esta información de manera estructurada a través de este parámetro
  profileId: string// Parámetro para proporcionar el ID del perfil del usuario que está realizando el escaneo de la actividad, lo que permite a esta función identificar al usuario que está intentando registrar su asistencia a una actividad específica, mejorando la gestión de las asistencias en la aplicación al permitir a los desarrolladores asociar las asistencias registradas con los perfiles de los usuarios de manera clara y estructurada
): Promise<ScanResult> => {// Tipo de retorno para indicar que esta función devuelve una promesa que se resuelve con un objeto de tipo ScanResult, lo que permite a esta función proporcionar la información del resultado del escaneo de la actividad de manera estructurada y clara, mejorando la gestión de los resultados en la aplicación al definir un tipo específico para el resultado de esta operación
  const { qr_payload } = data;// Desestructuración del objeto data para obtener el valor del payload de QR, lo que permite a esta función acceder al valor del payload de QR proporcionado en los datos de entrada de manera clara y estructurada, mejorando la gestión de los datos en la aplicación al proporcionar una forma sencilla de acceder a esta información específica dentro de la función

  const actividad = await getActividadByQrPayloadService(qr_payload);// Llamada al servicio getActividadByQrPayloadService para obtener la información de una actividad específica utilizando el payload de QR proporcionado, lo que permite a esta función obtener la información de la actividad correspondiente al payload de QR que se desea escanear para registrar la asistencia, mejorando la gestión de las actividades en la aplicación al delegar esta lógica de negocio a un servicio específico y centralizarla en ese servicio
  if (!actividad) throw Boom.badRequest("QR inválido o actividad no encontrada");// Verificación de que se ha encontrado una actividad correspondiente al payload de QR proporcionado, lo que permite a esta función validar que el payload de QR es válido y que existe una actividad asociada a ese payload, mejorando la gestión de errores en la aplicación al proporcionar una respuesta clara y específica en caso de que el payload de QR sea inválido o no se encuentre una actividad correspondiente

  const existing = await pool.query(//  Consulta SQL para verificar si el usuario ya ha registrado su asistencia a la actividad correspondiente al payload de QR proporcionado, lo que permite a esta función validar que el usuario no haya registrado su asistencia previamente a esa actividad, mejorando la gestión de las asistencias en la aplicación al evitar registros duplicados de asistencia para la misma actividad por parte del mismo usuario
    `SELECT id FROM asistencias WHERE profile_id = $1 AND actividad_id = $2 LIMIT 1`,// Consulta SQL para verificar si el usuario ya ha registrado su asistencia a la actividad correspondiente al payload de QR proporcionado, lo que permite a esta función validar que el usuario no haya registrado su asistencia previamente a esa actividad, mejorando la gestión de las asistencias en la aplicación al evitar registros duplicados de asistencia para la misma actividad por parte del mismo usuario
    [profileId, actividad.id]// Parámetros para proporcionar el ID del perfil del usuario y el ID de la actividad que se desea verificar para el registro de asistencia, lo que permite a esta función ejecutar la consulta SQL con estos valores específicos para validar si el usuario ya ha registrado su asistencia a esa actividad, mejorando la gestión de las asistencias en la aplicación al evitar registros duplicados de asistencia para la misma actividad por parte del mismo usuario
  );

  if (existing.rowCount && existing.rowCount > 0) {// Verificación de que se ha encontrado un registro de asistencia existente para el usuario y la actividad correspondiente, lo que permite a esta función validar que el usuario ya ha registrado su asistencia a esa actividad, mejorando la gestión de las asistencias en la aplicación al evitar registros duplicados de asistencia para la misma actividad por parte del mismo usuario y proporcionar una respuesta clara en caso de que esto ocurra
    throw Boom.conflict("Ya registraste tu asistencia a esta actividad");// Lanzamiento de un error HTTP con el código de estado 409 (Conflict) y un mensaje específico para indicar que el usuario ya ha registrado su asistencia a esa actividad, lo que permite a esta función responder al cliente con una información clara sobre el conflicto que ocurrió durante el proceso de registro de la asistencia, mejorando la gestión de errores en la aplicación al proporcionar información útil para que el cliente pueda entender y manejar los errores relacionados con los registros duplicados de asistencia
  }

  const result = await pool.query<Asistencia>(
    `INSERT INTO asistencias (profile_id, actividad_id, qr_payload_usado)
     VALUES ($1, $2, $3)
     RETURNING *`,
    [profileId, actividad.id, qr_payload]
  );

  return { asistencia: result.rows[0] };// Devuelve un objeto de tipo ScanResult que contiene la información del registro de asistencia que se ha insertado en la base de datos, lo que permite a esta función proporcionar la información del resultado del escaneo de la actividad de manera estructurada y clara, mejorando la gestión de los resultados en la aplicación al definir un tipo específico para el resultado de esta operación y proporcionar la información relevante sobre el registro de asistencia que se ha creado
};

export const getBalanceService = async (_profileId: string): Promise<number> => {// Función asíncrona para obtener el balance de asistencias de un usuario, lo que permite a esta función procesar la lógica relacionada con la obtención del balance de asistencias para un usuario específico, mejorando la gestión de las asistencias en la aplicación al proporcionar una función clara y estructurada para manejar esta operación
  return 0;// Devuelve un valor numérico que representa el balance de asistencias del usuario, lo que permite a esta función proporcionar la información del balance de asistencias de manera clara y estructurada, mejorando la gestión de las asistencias en la aplicación al definir un tipo específico para el resultado de esta operación y proporcionar la información relevante sobre el balance de asistencias del usuario
};

export const getHistorialService = async (profileId: string) => {// Función asíncrona para obtener el historial de asistencias de un usuario, lo que permite a esta función procesar la lógica relacionada con la obtención del historial de asistencias para un usuario específico, mejorando la gestión de las asistencias en la aplicación al proporcionar una función clara y estructurada para manejar esta operación
  const result = await pool.query(// Consulta SQL para obtener el historial de asistencias de un usuario específico, lo que permite a esta función obtener la información de las asistencias registradas por ese usuario en la base de datos, mejorando la gestión de las asistencias en la aplicación al proporcionar una forma clara y estructurada de obtener esta información desde la base de datos
    `SELECT a.*, act.titulo, act.fecha_inicio, act.fecha_fin, act.imagen_url
     FROM asistencias a
     JOIN actividades act ON act.id = a.actividad_id
     WHERE a.profile_id = $1
     ORDER BY a.escaneado_at DESC`,
    [profileId]
  );

  return result.rows;
};
